users = [
    [
        {
            "username": "o6bCimVa",
            "password": "iWH1nEBFYcN1",
            "email": "o6bCimVa@mail.com",
            "phone": "2299626341",
            "address": "463 Elm St, Lakeview, USA",
            "tags": ["premium"],
        },
        {
            "username": "Z6sIc7Yn",
            "password": "q20LLKRsSOG4",
            "email": "Z6sIc7Yn@mail.com",
            "phone": "8657488676",
            "address": "2 Elm St, Hilltop, USA",
            "tags": ["premium"],
        },
        {
            "username": "06Iw3Zw9",
            "password": "ib5Rib72JQTo",
            "email": "06Iw3Zw9@mail.com",
            "phone": "8604942582",
            "address": "658 Maple St, Rivertown, USA",
            "tags": ["user", "admin", "free"],
        },
        {
            "username": "OUkhLWRy",
            "password": "BvcML9NEeBkr",
            "email": "OUkhLWRy@example.com",
            "phone": "6733566208",
            "address": "653 Maple St, Fairview, USA",
            "tags": ["premium", "guest"],
        },
        {
            "username": "NVIKC48X",
            "password": "dm7O5S3RJMWE",
            "email": "NVIKC48X@demo.com",
            "phone": "4566184038",
            "address": "476 Maple St, Hilltop, USA",
            "tags": ["admin", "moderator"],
        },
        {
            "username": "zjl1odcr",
            "password": "8mzss1ECkVP3",
            "email": "zjl1odcr@demo.com",
            "phone": "9380410265",
            "address": "461 Elm St, Lakeview, USA",
            "tags": ["moderator", "free", "guest"],
        },
        {
            "username": "tCgA09CI",
            "password": "Tl6mLFoFTCZy",
            "email": "tCgA09CI@test.com",
            "phone": "4372244741",
            "address": "776 Maple St, Fairview, USA",
            "tags": ["user", "free"],
        },
        {
            "username": "wG2rNhWu",
            "password": "oB2lbTD6rOFv",
            "email": "wG2rNhWu@mail.com",
            "phone": "8264669093",
            "address": "552 High St, Rivertown, USA",
            "tags": ["moderator"],
        },
        {
            "username": "G26aFXGy",
            "password": "30Qz2tJNqJ78",
            "email": "G26aFXGy@demo.com",
            "phone": "0516480999",
            "address": "788 Maple St, Rivertown, USA",
            "tags": ["guest", "premium", "free"],
        },
        {
            "username": "2w4KtvzE",
            "password": "sNpMb68x7Ykw",
            "email": "2w4KtvzE@test.com",
            "phone": "1902155445",
            "address": "283 Main St, Rivertown, USA",
            "tags": ["admin"],
        },
        {
            "username": "nSmhiSKi",
            "password": "RyqcCaW9B34p",
            "email": "nSmhiSKi@example.com",
            "phone": "3182839529",
            "address": "229 Elm St, Rivertown, USA",
            "tags": ["premium", "admin", "free"],
        },
        {
            "username": "speRJZUd",
            "password": "x25YYhD3XcGI",
            "email": "speRJZUd@demo.com",
            "phone": "3528118670",
            "address": "18 High St, Lakeview, USA",
            "tags": ["premium"],
        },
        {
            "username": "5zladkcl",
            "password": "FlhJ8LBVjqPv",
            "email": "5zladkcl@demo.com",
            "phone": "7120096747",
            "address": "765 Maple St, Fairview, USA",
            "tags": ["user"],
        },
        {
            "username": "KQ86JmOU",
            "password": "WqQktTnPyEMZ",
            "email": "KQ86JmOU@test.com",
            "phone": "2925918505",
            "address": "699 Main St, Rivertown, USA",
            "tags": ["user", "moderator", "guest"],
        },
        {
            "username": "Wv2SehlZ",
            "password": "TOnMuLdxOstE",
            "email": "Wv2SehlZ@example.com",
            "phone": "0749324601",
            "address": "441 Maple St, Rivertown, USA",
            "tags": ["premium", "free", "admin"],
        },
        {
            "username": "Evxcb8qV",
            "password": "yQnD2tALjM0Q",
            "email": "Evxcb8qV@test.com",
            "phone": "3841058092",
            "address": "87 Main St, Rivertown, USA",
            "tags": ["user"],
        },
        {
            "username": "NXNMvPNY",
            "password": "8ZPVYIyzJCEL",
            "email": "NXNMvPNY@demo.com",
            "phone": "5347978758",
            "address": "639 Main St, Rivertown, USA",
            "tags": ["user", "moderator"],
        },
        {
            "username": "TCFdaqTO",
            "password": "sJ4aOb2yP2BU",
            "email": "TCFdaqTO@example.com",
            "phone": "3110887559",
            "address": "860 Elm St, Hilltop, USA",
            "tags": ["guest"],
        },
        {
            "username": "4zjNj6BE",
            "password": "sONPV046LWYC",
            "email": "4zjNj6BE@example.com",
            "phone": "0289467812",
            "address": "689 Maple St, Lakeview, USA",
            "tags": ["user", "premium", "admin"],
        },
        {
            "username": "faAjIbZb",
            "password": "dpOzYnc7dpsZ",
            "email": "faAjIbZb@example.com",
            "phone": "8028982632",
            "address": "927 High St, Hilltop, USA",
            "tags": ["user"],
        },
        {
            "username": "F2VbtOlb",
            "password": "qkc7f15sP2vH",
            "email": "F2VbtOlb@test.com",
            "phone": "7217636127",
            "address": "155 Oak St, Hilltop, USA",
            "tags": ["guest", "free"],
        },
        {
            "username": "kpPuNqii",
            "password": "ctGHq4lUfiRh",
            "email": "kpPuNqii@demo.com",
            "phone": "3189819568",
            "address": "502 High St, Springfield, USA",
            "tags": ["user"],
        },
        {
            "username": "5mnrm5Nj",
            "password": "IBuVFIfjDyfR",
            "email": "5mnrm5Nj@demo.com",
            "phone": "5615776745",
            "address": "858 Elm St, Springfield, USA",
            "tags": ["user"],
        },
        {
            "username": "2yLpppL9",
            "password": "WcSSlB2oqLwo",
            "email": "2yLpppL9@test.com",
            "phone": "4730598441",
            "address": "276 Main St, Fairview, USA",
            "tags": ["user", "free"],
        },
        {
            "username": "NHrp3L5U",
            "password": "QGOlbe7q2uGK",
            "email": "NHrp3L5U@example.com",
            "phone": "4623998254",
            "address": "426 Oak St, Fairview, USA",
            "tags": ["premium", "guest", "moderator"],
        },
        {
            "username": "dPXjJcJD",
            "password": "HKV6Zqxnm5RY",
            "email": "dPXjJcJD@mail.com",
            "phone": "9142756795",
            "address": "493 Main St, Rivertown, USA",
            "tags": ["user", "moderator", "premium"],
        },
        {
            "username": "ioooxDdG",
            "password": "nlKADxMp86lc",
            "email": "ioooxDdG@mail.com",
            "phone": "8514408421",
            "address": "111 High St, Fairview, USA",
            "tags": ["moderator", "admin"],
        },
        {
            "username": "jfkj3LDA",
            "password": "Z0ujnWdzEKrM",
            "email": "jfkj3LDA@test.com",
            "phone": "0363558393",
            "address": "684 Oak St, Lakeview, USA",
            "tags": ["premium", "guest", "free"],
        },
        {
            "username": "ju90UFQW",
            "password": "iFsPTVCxdSAr",
            "email": "ju90UFQW@test.com",
            "phone": "3549860046",
            "address": "894 Main St, Rivertown, USA",
            "tags": ["moderator"],
        },
        {
            "username": "XV7oFEGY",
            "password": "BoW0S0rB93cE",
            "email": "XV7oFEGY@mail.com",
            "phone": "6550463182",
            "address": "603 Maple St, Lakeview, USA",
            "tags": ["user", "moderator"],
        },
        {
            "username": "NKpSLlD4",
            "password": "T4AFwru6dr2a",
            "email": "NKpSLlD4@demo.com",
            "phone": "9171905343",
            "address": "834 Maple St, Springfield, USA",
            "tags": ["moderator"],
        },
        {
            "username": "alWNxpoA",
            "password": "IJYk69yuFWqZ",
            "email": "alWNxpoA@test.com",
            "phone": "2831090069",
            "address": "505 Main St, Lakeview, USA",
            "tags": ["guest", "moderator"],
        },
        {
            "username": "u0S08en9",
            "password": "iHAMmTVyWwCZ",
            "email": "u0S08en9@demo.com",
            "phone": "3064801446",
            "address": "450 Maple St, Fairview, USA",
            "tags": ["premium", "admin", "guest"],
        },
        {
            "username": "PAxTER5u",
            "password": "CslukOiCJMHv",
            "email": "PAxTER5u@example.com",
            "phone": "9468540312",
            "address": "8 Oak St, Fairview, USA",
            "tags": ["moderator", "free", "user"],
        },
        {
            "username": "DcLeyYHg",
            "password": "I4m0ItAFG0bS",
            "email": "DcLeyYHg@mail.com",
            "phone": "3177198203",
            "address": "873 Main St, Rivertown, USA",
            "tags": ["guest"],
        },
        {
            "username": "py58LD9v",
            "password": "9l3M7ORrx8RW",
            "email": "py58LD9v@mail.com",
            "phone": "9440959784",
            "address": "727 Oak St, Springfield, USA",
            "tags": ["admin", "moderator", "free"],
        },
        {
            "username": "eJvjjSmP",
            "password": "6gU0byTeeBey",
            "email": "eJvjjSmP@example.com",
            "phone": "0515366977",
            "address": "541 Maple St, Lakeview, USA",
            "tags": ["guest", "moderator"],
        },
        {
            "username": "cSqsPgg6",
            "password": "lBE313RxjKK7",
            "email": "cSqsPgg6@demo.com",
            "phone": "5195032979",
            "address": "899 Maple St, Springfield, USA",
            "tags": ["admin", "premium"],
        },
        {
            "username": "vfyEr3vZ",
            "password": "cWlBqjbqnLvm",
            "email": "vfyEr3vZ@test.com",
            "phone": "4339820754",
            "address": "475 Main St, Rivertown, USA",
            "tags": ["guest", "moderator"],
        },
        {
            "username": "vV0q0wog",
            "password": "22cmGm4KH2VD",
            "email": "vV0q0wog@test.com",
            "phone": "1988850122",
            "address": "259 Main St, Hilltop, USA",
            "tags": ["free"],
        },
        {
            "username": "n4dvhPQJ",
            "password": "tCz6nAaMnTxo",
            "email": "n4dvhPQJ@demo.com",
            "phone": "4708314528",
            "address": "896 High St, Hilltop, USA",
            "tags": ["guest"],
        },
        {
            "username": "yS2jKrPj",
            "password": "IoEA3LYNJbI2",
            "email": "yS2jKrPj@test.com",
            "phone": "6453647274",
            "address": "537 Oak St, Hilltop, USA",
            "tags": ["user"],
        },
        {
            "username": "tP5tY5FI",
            "password": "FQk6sQrIvz47",
            "email": "tP5tY5FI@demo.com",
            "phone": "2476504601",
            "address": "990 Oak St, Fairview, USA",
            "tags": ["admin"],
        },
        {
            "username": "23KldCZF",
            "password": "Guiqs2Gs3MPt",
            "email": "23KldCZF@test.com",
            "phone": "4301510712",
            "address": "321 Elm St, Rivertown, USA",
            "tags": ["free", "premium"],
        },
        {
            "username": "6K7aa22B",
            "password": "SkS0woezbu41",
            "email": "6K7aa22B@demo.com",
            "phone": "1713277589",
            "address": "580 Elm St, Rivertown, USA",
            "tags": ["user", "guest", "moderator"],
        },
        {
            "username": "fnGrvJc5",
            "password": "UQc97YYVlkFB",
            "email": "fnGrvJc5@mail.com",
            "phone": "8813679658",
            "address": "582 Maple St, Lakeview, USA",
            "tags": ["moderator", "guest", "free"],
        },
        {
            "username": "Vln4nfo8",
            "password": "Oy5pvZnjnwwX",
            "email": "Vln4nfo8@demo.com",
            "phone": "2870719241",
            "address": "261 Main St, Hilltop, USA",
            "tags": ["user"],
        },
        {
            "username": "d30G2GfQ",
            "password": "3yzJG0q9HlJ6",
            "email": "d30G2GfQ@example.com",
            "phone": "1169825313",
            "address": "704 High St, Lakeview, USA",
            "tags": ["user", "free"],
        },
        {
            "username": "nGmNhO4d",
            "password": "yHzQa24VdBez",
            "email": "nGmNhO4d@mail.com",
            "phone": "7251501951",
            "address": "306 Maple St, Fairview, USA",
            "tags": ["user", "premium", "guest"],
        },
        {
            "username": "Q1VHn2sv",
            "password": "fKvo6eVY95IH",
            "email": "Q1VHn2sv@demo.com",
            "phone": "8108429263",
            "address": "526 Maple St, Fairview, USA",
            "tags": ["guest", "admin", "premium"],
        },
    ],
    [
        {
            "username": "ioD5QAE9",
            "password": "672lgO37xSrO",
            "email": "ioD5QAE9@demo.com",
            "phone": "9223475215",
            "address": "264 Maple St, Fairview, USA",
            "tags": ["moderator", "premium"],
        },
        {
            "username": "1zEi7XW4",
            "password": "9otyrgf5HSMR",
            "email": "1zEi7XW4@example.com",
            "phone": "7378293643",
            "address": "659 Maple St, Hilltop, USA",
            "tags": ["premium"],
        },
        {
            "username": "L6magOpf",
            "password": "VxZXXZgmhEpI",
            "email": "L6magOpf@demo.com",
            "phone": "8709217836",
            "address": "28 Elm St, Rivertown, USA",
            "tags": ["user"],
        },
        {
            "username": "pXsDEOLS",
            "password": "BwKbmc7A2SfP",
            "email": "pXsDEOLS@test.com",
            "phone": "2100705432",
            "address": "66 Main St, Hilltop, USA",
            "tags": ["guest", "free"],
        },
        {
            "username": "rIj7ZS6W",
            "password": "f0xdrzLdMMNc",
            "email": "rIj7ZS6W@example.com",
            "phone": "3632967539",
            "address": "765 Main St, Rivertown, USA",
            "tags": ["premium", "admin"],
        },
        {
            "username": "TY2KKTzx",
            "password": "gr3W7qwH876b",
            "email": "TY2KKTzx@test.com",
            "phone": "9448236058",
            "address": "702 High St, Springfield, USA",
            "tags": ["premium", "free"],
        },
        {
            "username": "4uQaV7cA",
            "password": "oZ4Lx1ZscrRK",
            "email": "4uQaV7cA@test.com",
            "phone": "6676268184",
            "address": "372 Main St, Springfield, USA",
            "tags": ["moderator", "premium"],
        },
        {
            "username": "51f45Nlv",
            "password": "7JikU6c24bxS",
            "email": "51f45Nlv@example.com",
            "phone": "0889361123",
            "address": "194 Maple St, Lakeview, USA",
            "tags": ["premium", "free", "user"],
        },
        {
            "username": "YNlgEREO",
            "password": "gL7uyJBeLkXL",
            "email": "YNlgEREO@mail.com",
            "phone": "9889353175",
            "address": "570 Elm St, Lakeview, USA",
            "tags": ["premium", "admin"],
        },
        {
            "username": "fXA050eL",
            "password": "VR9mKTtldZne",
            "email": "fXA050eL@mail.com",
            "phone": "8286572543",
            "address": "390 High St, Springfield, USA",
            "tags": ["moderator", "premium", "guest"],
        },
        {
            "username": "hOr6Rgbn",
            "password": "lmU1RWjvQF61",
            "email": "hOr6Rgbn@mail.com",
            "phone": "2797370961",
            "address": "275 Elm St, Rivertown, USA",
            "tags": ["premium", "user"],
        },
        {
            "username": "Tm1EkKoj",
            "password": "mAr7awT4kk22",
            "email": "Tm1EkKoj@example.com",
            "phone": "7939367947",
            "address": "89 Oak St, Fairview, USA",
            "tags": ["premium", "moderator"],
        },
        {
            "username": "3wrvnWNr",
            "password": "lZra3F9qeQKy",
            "email": "3wrvnWNr@test.com",
            "phone": "9280309652",
            "address": "612 High St, Fairview, USA",
            "tags": ["premium"],
        },
        {
            "username": "XGC37Sgd",
            "password": "Ory7cA0VXQ12",
            "email": "XGC37Sgd@example.com",
            "phone": "6379483107",
            "address": "750 Main St, Lakeview, USA",
            "tags": ["moderator", "premium", "admin"],
        },
        {
            "username": "lergtwkK",
            "password": "ZDJ0h3PksAOt",
            "email": "lergtwkK@demo.com",
            "phone": "3075407213",
            "address": "879 Elm St, Rivertown, USA",
            "tags": ["free", "admin"],
        },
        {
            "username": "D5D91gYz",
            "password": "zzvZS8r1fdFL",
            "email": "D5D91gYz@mail.com",
            "phone": "7870121671",
            "address": "715 Maple St, Hilltop, USA",
            "tags": ["user", "admin"],
        },
        {
            "username": "Gsn8f1UW",
            "password": "2GLuYDVLOyBR",
            "email": "Gsn8f1UW@test.com",
            "phone": "6215464261",
            "address": "562 Main St, Hilltop, USA",
            "tags": ["admin", "moderator"],
        },
        {
            "username": "wzljvOYE",
            "password": "dZazLx4qlODI",
            "email": "wzljvOYE@example.com",
            "phone": "7840550652",
            "address": "748 Maple St, Rivertown, USA",
            "tags": ["admin"],
        },
        {
            "username": "xcop3LIA",
            "password": "kdVjt62XQTxY",
            "email": "xcop3LIA@mail.com",
            "phone": "8582995280",
            "address": "798 Maple St, Hilltop, USA",
            "tags": ["guest", "user"],
        },
        {
            "username": "BnCj5SO5",
            "password": "pveRpgAz41rv",
            "email": "BnCj5SO5@example.com",
            "phone": "5768590657",
            "address": "560 Maple St, Fairview, USA",
            "tags": ["moderator", "admin", "guest"],
        },
        {
            "username": "yqcipreL",
            "password": "KjVu4bFofah3",
            "email": "yqcipreL@example.com",
            "phone": "7041843497",
            "address": "925 Elm St, Fairview, USA",
            "tags": ["guest", "free", "premium"],
        },
        {
            "username": "vvuAz9J0",
            "password": "6qM1NxKiNK2x",
            "email": "vvuAz9J0@demo.com",
            "phone": "3251335276",
            "address": "161 Elm St, Rivertown, USA",
            "tags": ["premium", "admin"],
        },
        {
            "username": "YmlsCynW",
            "password": "QtPQRS1KRMkp",
            "email": "YmlsCynW@mail.com",
            "phone": "5661279364",
            "address": "826 Oak St, Lakeview, USA",
            "tags": ["user", "admin", "premium"],
        },
        {
            "username": "ExPsMxK0",
            "password": "oiirnLNPcWBs",
            "email": "ExPsMxK0@example.com",
            "phone": "0695458725",
            "address": "678 Oak St, Springfield, USA",
            "tags": ["admin"],
        },
        {
            "username": "j8oZGUgZ",
            "password": "jaUB1nuYZbqP",
            "email": "j8oZGUgZ@mail.com",
            "phone": "2574452957",
            "address": "404 Main St, Fairview, USA",
            "tags": ["free"],
        },
        {
            "username": "hlA4hMHQ",
            "password": "wEsb4kcwL9Qk",
            "email": "hlA4hMHQ@demo.com",
            "phone": "7235665636",
            "address": "123 Oak St, Rivertown, USA",
            "tags": ["premium", "free", "guest"],
        },
        {
            "username": "Kz8z1rxW",
            "password": "dcH0o1GAkKwO",
            "email": "Kz8z1rxW@example.com",
            "phone": "4648619932",
            "address": "239 Main St, Rivertown, USA",
            "tags": ["admin"],
        },
        {
            "username": "vS8u6xkK",
            "password": "jhl5wIKBTWfx",
            "email": "vS8u6xkK@mail.com",
            "phone": "6600913629",
            "address": "574 Maple St, Springfield, USA",
            "tags": ["moderator", "admin"],
        },
        {
            "username": "eSFZWJlY",
            "password": "15oce8toejJk",
            "email": "eSFZWJlY@demo.com",
            "phone": "7307246954",
            "address": "415 High St, Hilltop, USA",
            "tags": ["premium", "moderator"],
        },
        {
            "username": "WP0zm3Yj",
            "password": "OvAlABF5jKqI",
            "email": "WP0zm3Yj@demo.com",
            "phone": "1376506596",
            "address": "637 Main St, Fairview, USA",
            "tags": ["free"],
        },
        {
            "username": "HOqzXUOL",
            "password": "PmYrQoqcB1Yb",
            "email": "HOqzXUOL@mail.com",
            "phone": "7977899928",
            "address": "839 Elm St, Springfield, USA",
            "tags": ["guest", "user"],
        },
        {
            "username": "8Y0F2hkZ",
            "password": "vYB0SxVreX0W",
            "email": "8Y0F2hkZ@mail.com",
            "phone": "1872847694",
            "address": "891 Main St, Springfield, USA",
            "tags": ["admin", "free"],
        },
        {
            "username": "9yg5e6TB",
            "password": "H5elwpiKxsnN",
            "email": "9yg5e6TB@demo.com",
            "phone": "0983732026",
            "address": "240 Oak St, Lakeview, USA",
            "tags": ["user", "admin", "free"],
        },
        {
            "username": "W6n9BZhh",
            "password": "C1AJZN8s5aPO",
            "email": "W6n9BZhh@mail.com",
            "phone": "2472675906",
            "address": "618 Main St, Rivertown, USA",
            "tags": ["premium", "free"],
        },
        {
            "username": "qO0Xq4b4",
            "password": "KpmGy7BAHIHI",
            "email": "qO0Xq4b4@demo.com",
            "phone": "4501825068",
            "address": "486 Elm St, Fairview, USA",
            "tags": ["moderator", "guest", "premium"],
        },
        {
            "username": "AbYTIPSM",
            "password": "uqnBhAJ6mSdv",
            "email": "AbYTIPSM@demo.com",
            "phone": "9392353647",
            "address": "517 High St, Lakeview, USA",
            "tags": ["admin"],
        },
        {
            "username": "hppiqEvn",
            "password": "52qKf6VBNNCr",
            "email": "hppiqEvn@mail.com",
            "phone": "1631972513",
            "address": "450 Elm St, Springfield, USA",
            "tags": ["moderator", "premium"],
        },
        {
            "username": "aLDUH6hl",
            "password": "1I4fWvSsTQna",
            "email": "aLDUH6hl@example.com",
            "phone": "3198618332",
            "address": "986 High St, Springfield, USA",
            "tags": ["guest", "free", "premium"],
        },
        {
            "username": "voWY1u57",
            "password": "iLfUe0pX0MaH",
            "email": "voWY1u57@test.com",
            "phone": "5161908549",
            "address": "436 Elm St, Fairview, USA",
            "tags": ["moderator", "admin"],
        },
        {
            "username": "LnCh7t1b",
            "password": "DJwbVt4uTB1R",
            "email": "LnCh7t1b@example.com",
            "phone": "5833008980",
            "address": "140 Main St, Springfield, USA",
            "tags": ["admin"],
        },
        {
            "username": "xLV5gpix",
            "password": "TVH6SzNGknrg",
            "email": "xLV5gpix@demo.com",
            "phone": "7206019036",
            "address": "477 Maple St, Fairview, USA",
            "tags": ["user", "free"],
        },
        {
            "username": "dpugAJ2l",
            "password": "oZeaCvnvrOJ5",
            "email": "dpugAJ2l@test.com",
            "phone": "1986314633",
            "address": "47 Oak St, Rivertown, USA",
            "tags": ["moderator"],
        },
        {
            "username": "6d89yskK",
            "password": "BYj0QJOhRpog",
            "email": "6d89yskK@test.com",
            "phone": "2593353086",
            "address": "611 Oak St, Springfield, USA",
            "tags": ["admin"],
        },
        {
            "username": "8lZxIWv1",
            "password": "r7hFGKaYPDD5",
            "email": "8lZxIWv1@test.com",
            "phone": "6960837407",
            "address": "878 Elm St, Hilltop, USA",
            "tags": ["admin"],
        },
        {
            "username": "OlpuWGrD",
            "password": "rshkuIrYfcH0",
            "email": "OlpuWGrD@demo.com",
            "phone": "1809800392",
            "address": "877 Oak St, Fairview, USA",
            "tags": ["moderator", "premium"],
        },
        {
            "username": "rM75nUN3",
            "password": "aTWSokwtgGQB",
            "email": "rM75nUN3@example.com",
            "phone": "4279114968",
            "address": "170 Elm St, Rivertown, USA",
            "tags": ["admin", "free"],
        },
        {
            "username": "IgkO9LRj",
            "password": "BWfDzqUFIS4f",
            "email": "IgkO9LRj@demo.com",
            "phone": "7367848174",
            "address": "98 Main St, Springfield, USA",
            "tags": ["guest", "admin"],
        },
        {
            "username": "kaxD3ezU",
            "password": "d4xUMgteV4jx",
            "email": "kaxD3ezU@test.com",
            "phone": "2566522322",
            "address": "37 Oak St, Springfield, USA",
            "tags": ["admin", "guest", "premium"],
        },
        {
            "username": "NBL2zLhE",
            "password": "XnfhabXfzhoV",
            "email": "NBL2zLhE@mail.com",
            "phone": "4751584776",
            "address": "483 High St, Rivertown, USA",
            "tags": ["premium"],
        },
        {
            "username": "L4SMZEzx",
            "password": "ZfMDAbwtGcdD",
            "email": "L4SMZEzx@example.com",
            "phone": "6458556179",
            "address": "922 Maple St, Fairview, USA",
            "tags": ["premium"],
        },
    ],
]
